export { default as hyundai_mobis } from './hyundai_mobis.png'
export { default as samsung } from './samsung.svg'
export { default as lg } from './lg.png'
export { default as naver } from './naver.png'
export { default as line } from './line.png'
